---
- name: Reboot system
  listen: Reboot system
  vars:
    _additional_timeout_tor: "{{ tor_port > 0 | ternary(60, 0) }}"
  ansible.builtin.reboot:
    reboot_timeout: "{{ 60 + _additional_timeout_tor | int }}"
    post_reboot_delay: 30
    test_command: "iptables -nvL"
