---
- name: Check for a known coredump
  delegate_to: localhost
  throttle: 1
  ansible.builtin.lineinfile:
    line: "{{ _unique_id }}"
    path: "{{ infodir }}/coredump/_known.txt"
  register: __known

- name: Work on new coredump
  when: __known.changed
  block:
    - name: Get coredump info
      changed_when: false
      ansible.builtin.shell:
        cmd: |-
          tar -xf {{ _fname }} --to-stdout >/tmp/core
          gdb -q -batch \
            -ex 'set logging enabled off' -ex 'set pagination off' -ex 'thread apply all bt' -ex 'quit' \
            -c /tmp/core
          echo
          echo "-----------------------------------"
          echo
          eu-stack --core /tmp/core
          rm /tmp/core
      register: __info
      notify: Not Healthy

    - name: File coredump info
      delegate_to: localhost
      throttle: "{{ concurrent_local_jobs }}"
      ansible.builtin.copy:
        content: "{{ __info.stdout }}"
        dest: "{{ infodir }}/coredump/{{ _unique_id }}.txt"

  rescue:
    - name: Reset known state for coredump
      delegate_to: localhost
      throttle: 1
      ansible.builtin.lineinfile:
        line: "{{ _unique_id }}"
        path: "{{ infodir }}/coredump/_known.txt"
        state: absent

  always:
    - name: Get dmesg for coredump
      ansible.builtin.include_tasks: _dmesg.yaml

    - name: Get kernel config for coredump
      ansible.builtin.include_tasks: _kconfig.yaml
