---
# https://unix.stackexchange.com/questions/178626/how-to-run-unattended-upgrades-not-daily-but-every-few-hours
- name: Configure unattended upgrade
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/apt/apt.conf.d/
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades
  notify: Reload systemd

- name: Enable unattended upgrade
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    state: started
  loop:
    - apt-daily.timer
    - apt-daily-upgrade.timer
    - unattended-upgrades
