---
- name: Gather facts - uptime
  ansible.builtin.setup:
    gather_subset:
      - hardware

- name: Sum connections
  changed_when: false
  failed_when: false
  ansible.builtin.shell:
    cmd: |-
      set -eu

      equatation=$(
        set -o pipefail

        journalctl -u {{ item.name }} --since "{{ log_connections_seconds_ago }} second ago" \
          -g ', there were .* connections' --quiet |
        awk '{ print $14 }' |
        xargs -r |
        tr ' ' '+'
      )
      echo $(( equatation ))
    executable: /bin/bash
  register: _result

- name: File connections
  delegate_to: localhost
  throttle: 1
  ansible.builtin.lineinfile:
    line: "{{ inventory_hostname }} {{ _result.stdout | default('n/a') }}"
    path: "{{ infodir }}/{{ item.name }}_connections"
    regexp: "^{{ inventory_hostname }} "
    state: "{{ (item.state == 'present' and _result.stderr | length == 0) | ternary('present', 'absent') }}"
