---
- name: Get process runtime
  changed_when: false
  ansible.builtin.shell:
    cmd: |-
      ps -eo etimes,cmd --no-headers |
        grep " /usr/bin/{{ item.name }} " |
        grep -v " grep " |
        awk '{ printf("%i-%02i\n", $1 / 86400, $1 % 86400 / 3600) }'
  register: _result

- name: File process runtime
  delegate_to: localhost
  throttle: 1
  ansible.builtin.lineinfile:
    line: "{{ inventory_hostname }} etimes {{ _result.stdout | default('-') }}"
    path: "{{ infodir }}/{{ item.name }}_process_runtime"
    regexp: "^{{ inventory_hostname }} "
    state: "{{ (item.state == 'present' and _result.stdout | length > 0) | ternary('present', 'absent') }}"
