---
- name: Snowflake version
  changed_when: false
  ansible.builtin.shell:
    cmd: |-
      /usr/bin/{{ item.name }} --version 2>&1 |
        head -n 1 |
        cut -f 2- -d ' ' |
        tr ' ' '_'
  register: _result

- name: File version
  delegate_to: localhost
  throttle: 1
  vars:
    _version: "{{ _result.stdout | default('-') }}"
  ansible.builtin.lineinfile:
    line: "{{ inventory_hostname }} sf {{ _version }}"
    path: "{{ infodir }}/{{ item.name }}_version"
    regexp: "^{{ inventory_hostname }} "
    state: "{{ (item.state == 'present' and _result.stdout | length > 0) | ternary('present', 'absent') }}"
