---
- name: Test common
  hosts: all
  roles:
    - role: poweron
    - role: setup_common

- name: Test snowflake
  hosts: snowflake
  roles:
    - role: setup_snowflake

- name: Test tor
  hosts: tor
  roles:
    - role: setup_tor

- name: Test final
  hosts: all
  roles:
    - role: setup_autoupdate
    - role: info_healthy

- name: Test end
  hosts: all
  roles:
    - role: shutdown
    - role: snapshot
    - role: delete
