---
- name: Test image
  hosts: all
  roles:
    - role: poweron
    - role: setup_common
    - role: setup_kernel
    - role: info_healthy
    - role: shutdown
    - role: snapshot
    - role: delete
