---
- name: Test common
  hosts: hx
  order: shuffle
  roles:
    - role: setup_common
    - role: info_common

- name: Test Snowflake
  hosts: hsx
  order: shuffle
  roles:
    - role: setup_snowflake

- name: Test Tor
  hosts: htx
  order: shuffle
  roles:
    - role: setup_tor

- name: Test Snowflake info
  hosts: hsx
  order: shuffle
  roles:
    - role: info_snowflake

- name: Test Tor info
  hosts: htx
  order: shuffle
  roles:
    - role: info_tor

- name: Test kernel
  hosts: hx
  order: shuffle
  roles:
    - role: setup_kernel
    - role: setup_autoupdate
    - role: info_healthy
    - role: delete
