---
- name: Test common
  hosts: all
  roles:
    - role: poweron
    - role: setup_common
    - role: info_common

- name: Test Snowflake
  hosts: snowflake
  roles:
    - role: setup_snowflake

- name: Test Snowflake info
  hosts: snowflake
  roles:
    - role: info_snowflake

- name: Test Tor
  hosts: tor
  roles:
    - role: setup_tor

- name: Test Tor info
  hosts: tor
  roles:
    - role: info_tor

- name: Test finish
  hosts: all
  roles:
    - role: setup_kernel
    - role: setup_autoupdate
    - role: info_healthy
    - role: delete
