---
- name: Setup common
  hosts: all
  roles:
    - role: poweron
    - role: setup_common

- name: Setup snowflake
  hosts: snowflake
  roles:
    - role: setup_snowflake

- name: Setup tor
  hosts: tor
  roles:
    - role: setup_tor

- name: Setup autoupdate
  hosts: all
  roles:
    - role: setup_kernel
    - role: setup_autoupdate
    - role: info_healthy
    - role: delete
