---
- name: Test common
  hosts: all
  roles:
    - role: poweron
    - role: setup_common

- name: Test snowflake
  hosts: snowflake
  roles:
    - role: setup_snowflake

- name: Test tor
  hosts: tor
  roles:
    - role: setup_tor

- name: Test all
  hosts: all
  roles:
    - role: setup_autoupdate
    - role: info_healthy
    - role: delete
